name: my_flutter_app
description: "A new Flutter project with localization."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.0
  

  # Flutter localization dependencies
  flutter_localizations:
    sdk: flutter

  # Internationalization package for working with other formats
  intl: ^0.19.0 # or use a newer version if needed

  # For Cupertino icons (optional)
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.4
  simple_barcode_scanner: ^0.2.5
  flutter_scalable_ocr: ^2.2.0 
  image_picker: ^0.8.5+3
  permission_handler: ^11.3.1
  http: ^1.2.2
  flutter_gemini: ^3.0.0
  cached_network_image: ^3.2.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting rules
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/tesseract/
     - assets/images/03_06_2024_16_47_55_7292632.png
flutter_intl:
  enabled: true
