// lib/cor/util/food_keywords.dart

const List<String> foodKeywords = [
    'food',
    'safety',
    'contamination',
    'label',
    'recall',
    'foodborne',
    'allergen',
    'nutrition',
    'rights',
    'diet',
    'foodborne illness',
    'gastronomy',
    'organic food',
    'processed food',
    'whole food',
    'superfoods',
    'culinary',
    'ethnic foods',
    'vegan',
    'vegetarian',
    'gluten-free',
    'low-carb',
    'paleo',
    'plant-based',
    'raw food',
    'farm-to-table',
    'healthy eating',
    'food labeling',
    'food additives',
    'food preservation',
    'food standards',
    'food packaging',
    'fermented food',
    'functional foods',
    'nutritional supplements',
    'vitamins',
    'minerals',
    'herbal supplements',
    'dietary supplements',
    'probiotics',
    'amino acids',
    'omega-3 fatty acids',
    'protein powders',
    'energy supplements',
    'weight loss supplements',
    'sports supplements',
    'pre-workout supplements',
    'post-workout supplements',
    'detox supplements',
    'multivitamins',
    'consumer rights',
    'consumer safety',
    'product recalls',
    'labeling laws',
    'fair trade',
    'consumer advocacy',
    'consumer law',
    'consumer fraud',
    'consumer complaints',
    'consumer protection agency',
    'truth-in-advertising laws',
    'product safety standards',
    'warranty',
    'refund policy',
    'scam prevention',
    'class action lawsuits',
    'food allergy',
    'allergen',
    'anaphylaxis',
    'peanut allergy',
    'dairy allergy',
    'gluten allergy',
    'egg allergy',
    'shellfish allergy',
    'tree nut allergy',
    'soy allergy',
    'wheat allergy',
    'food intolerance',
    'cross-contamination',
    'allergen labeling',
    'hypersensitivity',
    'epipen',
    'non-allergic food reactions',
    'food allergy testing',
    'food safety practices',
    'famous product nutrition',
    'famous product in Algeria',
    'fruits',
    'Allergies',
    'food-related diseases',
    'salmonella',
    'E. coli',
    'Listeria',
    'Norovirus',
    'Hepatitis A',
    'Campylobacter',
    'Botulism',
    'Vibrio',
    'Shigella',
    'Cryptosporidiosis',
    'Giardiasis',
    'Ciguatera fish poisoning',
    'Toxoplasmosis',
    'Trichinosis',
    'Mad cow disease',
    'Food poisoning',
    'aliments',
    'sécurité',
    'contamination',
    'étiquette',
    'rappel',
    'maladies d\'origine alimentaire',
    'allergène',
    'nutrition',
    'droits',
    'régime',
    'maladie d\'origine alimentaire',
    'gastronomie',
    'aliments biologiques',
    'aliments transformés',
    'aliments complets',
    'super-aliments',
    'culinaire',
    'aliments ethniques',
    'végétalien',
    'végétarien',
    'sans gluten',
    'pauvre en glucides',
    'paléo',
    'à base de plantes',
    'aliments crus',
    'ferme à table',
    'alimentation saine',
    'étiquetage des aliments',
    'additifs alimentaires',
    'conservation des aliments',
    'normes alimentaires',
    'emballage des aliments',
    'aliments fermentés',
    'aliments fonctionnels',
    'compléments alimentaires',
    'vitamines',
    'minéraux',
    'compléments à base de plantes',
    'compléments alimentaires',
    'probiotiques',
    'acides aminés',
    'acides gras oméga-3',
    'poudres de protéines',
    'compléments énergétiques',
    'compléments de perte de poids',
    'compléments sportifs',
    'compléments pré-entraînement',
    'compléments post-entraînement',
    'compléments détox',
    'multivitamines',
    'droits des consommateurs',
    'sécurité des consommateurs',
    'rappels de produits',
    'lois sur l\'étiquetage',
    'commerce équitable',
    'défense des consommateurs',
    'droit des consommateurs',
    'fraude des consommateurs',
    'plaintes des consommateurs',
    'agence de protection des consommateurs',
    'lois sur la publicité véridique',
    'normes de sécurité des produits',
    'garantie',
    'politique de remboursement',
    'prévention des escroqueries',
    'actions collectives',
    'allergie alimentaire',
    'allergène',
    'anaphylaxie',
    'allergie aux arachides',
    'allergie au lait',
    'allergie au gluten',
    'allergie aux œufs',
    'allergie aux crustacés',
    'allergie aux noix',
    'allergie au soja',
    'allergie au blé',
    'intolérance alimentaire',
    'contamination croisée',
    'étiquetage des allergènes',
    'hypersensibilité',
    'epipen',
    'réactions alimentaires non allergiques',
    'tests d\'allergie alimentaire',
    'pratiques de sécurité alimentaire',
    'nutrition des produits célèbres',
    'produit célèbre en Algérie',
    'fruits',
    'Allergies',
    'maladies liées à l\'alimentation',
    'salmonelle',
    'E. coli',
    'Listeria',
    'Norovirus',
    'Hépatite A',
    'Campylobacter',
    'Botulisme',
    'Vibrio',
    'Shigella',
    'Cryptosporidiose',
    'Giardiasis',
    'Intoxication alimentaire ciguatera',
    'Toxoplasmose',
    'Trichinose',
    'Maladie de la vache folle',
    'Intoxication alimentaire'
    'طعام',
    'أمان',
    'تلوث',
    'تسمية',
    'استرجاع',
    'أمراض منقولة عن الطعام',
    'مادة مسببة للحساسية',
    'تغذية',
    'حقوق',
    'حمية',
    'أمراض منقولة عن الطعام',
    'فن الطهو',
    'الطعام العضوي',
    'الطعام المعالج',
    'الطعام الكامل',
    'الأطعمة الخارقة',
    'الطعام العرقي',
    'نباتي',
    'نباتي (خالي من منتجات الألبان)',
    'خالي من الغلوتين',
    'قليل الكربوهيدرات',
    'باليو',
    'قائم على النباتات',
    'طعام خام',
    'من المزرعة إلى المائدة',
    'أكل صحي',
    'تصنيف الطعام',
    'الإضافات الغذائية',
    'حفظ الطعام',
    'معايير الطعام',
    'تعبئة الطعام',
    'الطعام المخمر',
    'الأطعمة الوظيفية',
    'المكملات الغذائية',
    'فيتامينات',
    'معادن',
    'المكملات العشبية',
    'مكملات غذائية',
    'بروبيوتيك',
    'أحماض أمينية',
    'أحماض دهنية أوميغا-3',
    'مساحيق البروتين',
    'مكملات الطاقة',
    'مكملات فقدان الوزن',
    'مكملات رياضية',
    'مكملات قبل التمرين',
    'مكملات ما بعد التمرين',
    'مكملات إزالة السموم',
    'الفيتامينات المتعددة',
    'حقوق المستهلك',
    'أمان المستهلك',
    'استرجاع المنتجات',
    'قوانين التصنيف',
    'التجارة العادلة',
    'دفاع المستهلك',
    'قانون المستهلك',
    'احتيال المستهلك',
    'شكاوى المستهلكين',
    'وكالة حماية المستهلك',
    'قوانين الإعلان الصادق',
    'معايير سلامة المنتجات',
    'ضمان',
    'سياسة الاسترجاع',
    'الوقاية من الاحتيال',
    'الدعاوى الجماعية',
    'حساسية الطعام',
    'مادة مسببة للحساسية',
    'التفاعل التحسسي',
    'حساسية الفول السوداني',
    'حساسية الألبان',
    'حساسية الغلوتين',
    'حساسية البيض',
    'حساسية المأكولات البحرية',
    'حساسية المكسرات',
    'حساسية الصويا',
    'حساسية القمح',
    'التسمم الغذائي',
    'التلوث المتقاطع',
    'تصنيف المواد المسببة للحساسية',
    'فرط الحساسية',
    'إبينيفرين',
    'ردود الفعل غير التحسسية للطعام',
    'اختبارات حساسية الطعام',
    'ممارسات سلامة الطعام',
    'تغذية المنتجات الشهيرة',
    'منتج مشهور في الجزائر',
    'الفواكه',
    'حساسية',
    'الأمراض المرتبطة بالطعام',
    'السالمونيلا',
    'إي كولاي',
    'ليستيريا',
    'نوروفيروس',
    'التهاب الكبد أ',
    'كامبيلوباكتر',
    'التيتانوس',
    'فابريكا',
    'شيجيلا',
    'التسمم الغذائي السجيترا',
    'التوكسوبلازما',
    'التريكينوس',
    'مرض جنون البقر',
    'تسمم غذائي'


];
